name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-edit
        run: cargo install cargo-edit --locked

      - name: Compute version
        id: meta
        run: |
          COUNT=$(git rev-list --count HEAD)
          VERSION="1.0.${COUNT}"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Apply workspace version
        run: cargo set-version --workspace ${{ steps.meta.outputs.version }}

      - name: Tests before publish
        run: cargo test --workspace --all-features

      - name: Publish crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          set -euo pipefail
          for manifest in \
            crates/proto/Cargo.toml \
            crates/crypto/Cargo.toml \
            crates/federation/Cargo.toml \
            crates/storage/Cargo.toml \
            crates/ledger/Cargo.toml
          do
            cargo publish --allow-dirty --manifest-path "$manifest"
            # give crates.io a moment to ingest the upload
            sleep 20
          done

      - name: Build release binary
        run: cargo build --release -p commucat-server

      - name: Package binary
        run: |
          mkdir -p dist
          cp target/release/commucat-server dist/
          strip dist/commucat-server || true
          cp README.md dist/README.md
          tar -czf commucat-server-linux-amd64.tar.gz -C dist commucat-server README.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: commucat-server-${{ steps.meta.outputs.version }}
          path: |
            target/release/commucat-server
            commucat-server-linux-amd64.tar.gz

      - name: Publish GitHub release asset
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          files: commucat-server-linux-amd64.tar.gz
          tag_name: v${{ steps.meta.outputs.version }}
          generate_release_notes: true

      - name: Summary
        run: |
          echo "Published crates at version ${{ steps.meta.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Release tarball: commucat-server-linux-amd64.tar.gz" >> $GITHUB_STEP_SUMMARY
